// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmYPvq2NeMBV55ojDB3Olk7Ijym2XOHyY',
    appId: '1:724136759646:web:8b86482f9165e27eef7fcf',
    messagingSenderId: '724136759646',
    projectId: 'bookdone-3a0d1',
    authDomain: 'bookdone-3a0d1.firebaseapp.com',
    storageBucket: 'bookdone-3a0d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiPQgBt-tsVcYRxX44JP1Fp1Nz5v_G6mM',
    appId: '1:724136759646:android:5c952cefcbe5e500ef7fcf',
    messagingSenderId: '724136759646',
    projectId: 'bookdone-3a0d1',
    storageBucket: 'bookdone-3a0d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGg7lcpZfGwhbHDoZQbhl4MrUMCwZ6oQ0',
    appId: '1:724136759646:ios:87bee1025893bed6ef7fcf',
    messagingSenderId: '724136759646',
    projectId: 'bookdone-3a0d1',
    storageBucket: 'bookdone-3a0d1.appspot.com',
    iosBundleId: 'com.example.bookdone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGg7lcpZfGwhbHDoZQbhl4MrUMCwZ6oQ0',
    appId: '1:724136759646:ios:ca61d13992488456ef7fcf',
    messagingSenderId: '724136759646',
    projectId: 'bookdone-3a0d1',
    storageBucket: 'bookdone-3a0d1.appspot.com',
    iosBundleId: 'com.example.bookdone.RunnerTests',
  );
}
